### ISSUE TITLE
Not loading Java..

### ISSUE THREAD

**Issue by alorg** [ffd114/gw2route#3]
Hi I am getting this error message...

Java Virtual Machine Launcher
Error: opening registry key 'Software\JavaSoft\Java Runtime Enviroment'

Error: could not find java.dll

Error: Could not find Java SE Runtime Enviroment.

I am not certain why I get this error... BUT I am wondering if this works with Google Chrome as it is based off Chromium, 

Also I have allocated java to a specific folder when I installed it. Could this be why I cannot load the Batch File? If so would you mind assisting me in editing the .bat file... Thanks in advance

**Comment by ffd114** [comment]
Can you make sure java location is exist in system PATH?

**Comment by alorg** [comment]
Not sure what you mean but this is the location I installed it.

"C:\Program Files\03 Internet\Java\jre1.8.0_66"

Then its as usual..... bin\

I use other programs that require Java and they work fine. I am sure its because I did not install it as default.  
and the batch file is probably looking for it in its default location.

**Comment by ffd114** [comment]
Try typing `java -version` from command prompt, it should show you java version if java location does exist in system PATH

For system PATH, you could refer to here: https://www.java.com/en/download/help/path.xml

Alternatively:
You can try to change `javaw` in batch file line 2 into `"C:\Program Files\03 Internet\Java\jre1.8.0_66\bin\javaw"` so it will shown like this:

`start "C:\Program Files\03 Internet\Java\jre1.8.0_66\bin\javaw" -cp "lib/*;gw2route.jar" -Djava.library.path=./libcef/win64 org.lunarproject.gw2route.Main`

Not sure if it will work though, didn't try it

**Comment by alorg** [comment]
Thanks will try this today or tomorrow when I have a moment and update you

**Comment by alorg** [comment]
All working Thanks : )
